// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvxjsjobvhbdnescgwrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2eGpzam9idmhiZG5lc2Nnd3JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMzEyMzUsImV4cCI6MjA1NzYwNzIzNX0._Vrhu4A4s_GC3wvBg2oakXiWgYQ7VWCyZvhXoV6Wxgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    db: {
      schema: 'public',
    },
    global: {
      headers: {
        'Content-Type': 'application/json',
      },
    },
    realtime: {
      params: {
        eventsPerSecond: 5,
      },
    }
  }
);

// Static data for presentations
export const staticDemoData = {
  events: [
    {
      id: "1",
      title: "Tech Summit 2024",
      description: "Annual technology conference featuring the latest innovations and industry trends",
      date: "2024-10-15",
      time: "09:00",
      venue: "Convention Center",
      capacity: 500,
      status: "upcoming",
      created_by: "1",
      event_speakers: [
        { name: "Jane Smith" },
        { name: "John Doe" },
        { name: "Alex Johnson" }
      ]
    },
    {
      id: "2",
      title: "AI Workshop",
      description: "Hands-on workshop on implementing machine learning models",
      date: "2024-07-22",
      time: "13:30", 
      venue: "Innovation Hub",
      capacity: 150,
      status: "upcoming",
      created_by: "1",
      event_speakers: [
        { name: "Maria Garcia" },
        { name: "Sam Wilson" }
      ]
    },
    {
      id: "3",
      title: "Developer Conference",
      description: "Conference for software developers with talks on emerging technologies",
      date: "2024-08-05",
      time: "10:00",
      venue: "Tech Campus",
      capacity: 300,
      status: "upcoming",
      created_by: "2", 
      event_speakers: [
        { name: "Thomas Lee" },
        { name: "Rachel Chen" }
      ]
    },
    {
      id: "4",
      title: "Startup Pitch Day",
      description: "Entrepreneurs present their startup ideas to potential investors",
      date: "2024-09-18",
      time: "14:00",
      venue: "Business Center",
      capacity: 200,
      status: "upcoming",
      created_by: "2",
      event_speakers: [
        { name: "David Brown" }
      ]
    },
    {
      id: "5",
      title: "Design Thinking Workshop",
      description: "Learn the principles of design thinking and apply them to real-world problems",
      date: new Date().toISOString().split('T')[0], // Today
      time: "11:00",
      venue: "Creative Studio",
      capacity: 100,
      status: "ongoing",
      created_by: "1",
      event_speakers: [
        { name: "Sophie Martin" }
      ]
    }
  ],
  users: [
    {
      id: "1",
      name: "Admin User",
      email: "admin@eventflow.com",
      role: "admin",
      created_at: "2024-01-15T10:00:00Z"
    },
    {
      id: "2",
      name: "Event Organizer",
      email: "organizer@eventflow.com",
      role: "organizer",
      created_at: "2024-01-20T14:30:00Z"
    },
    {
      id: "3",
      name: "John Attendee",
      email: "john@gmail.com",
      role: "attendee",
      created_at: "2024-02-05T09:15:00Z"
    },
    {
      id: "4",
      name: "Sarah Participant",
      email: "sarah@outlook.com",
      role: "attendee",
      created_at: "2024-02-10T16:45:00Z"
    },
    {
      id: "5",
      name: "Michael Jones",
      email: "michael@yahoo.com",
      role: "attendee",
      created_at: "2024-02-15T11:20:00Z"
    },
    {
      id: "6",
      name: "Lisa Williams",
      email: "lisa@gmail.com",
      role: "attendee",
      created_at: "2024-02-20T13:10:00Z"
    },
    {
      id: "7",
      name: "Robert Davis",
      email: "robert@outlook.com",
      role: "organizer",
      created_at: "2024-02-25T10:30:00Z"
    }
  ],
  notifications: [
    {
      id: "1",
      title: "New Event Added",
      message: "Tech Summit 2024 has been added to the schedule",
      type: "announcement",
      read: false,
      created_at: "2024-06-01T08:30:00Z",
      user_id: "3"
    },
    {
      id: "2",
      title: "Microphone Request Approved",
      message: "Your microphone request for the AI Workshop has been approved",
      type: "mic_request",
      read: true,
      created_at: "2024-05-28T14:15:00Z",
      user_id: "3"
    },
    {
      id: "3",
      title: "Event Update",
      message: "The venue for Developer Conference has been changed to Tech Campus",
      type: "event_update",
      read: false,
      created_at: "2024-05-25T09:45:00Z",
      user_id: "3"
    },
    {
      id: "4",
      title: "Feedback Response",
      message: "Your feedback about audio issues during the last workshop has been addressed",
      type: "complaint",
      read: false,
      created_at: "2024-05-20T11:00:00Z",
      user_id: "3"
    },
    {
      id: "5",
      title: "New Speaker Announcement",
      message: "Dr. Jane Smith will be joining as a keynote speaker for Tech Summit 2024",
      type: "announcement",
      read: false,
      created_at: "2024-05-15T16:30:00Z",
      user_id: "3"
    }
  ],
  micRequests: [
    {
      id: "1",
      event_id: "1",
      user_id: "3",
      reason: "I would like to ask a question about AI implementation",
      status: "pending",
      created_at: "2024-05-28T10:15:00Z",
      profiles: { name: "John Attendee" },
      events: { title: "Tech Summit 2024" }
    },
    {
      id: "2",
      event_id: "2",
      user_id: "4",
      reason: "I have a suggestion regarding the workshop content",
      status: "approved",
      created_at: "2024-05-27T09:30:00Z",
      profiles: { name: "Sarah Participant" },
      events: { title: "AI Workshop" }
    },
    {
      id: "3",
      event_id: "3",
      user_id: "5",
      reason: "I would like to share my experience with the discussed technology",
      status: "pending",
      created_at: "2024-05-26T14:45:00Z",
      profiles: { name: "Michael Jones" },
      events: { title: "Developer Conference" }
    },
    {
      id: "4",
      event_id: "1",
      user_id: "6",
      reason: "I need to clarify a point about the presentation",
      status: "denied",
      created_at: "2024-05-25T11:20:00Z",
      profiles: { name: "Lisa Williams" },
      events: { title: "Tech Summit 2024" }
    }
  ],
  complaints: [
    {
      id: "1",
      event_id: "1",
      user_id: "3",
      issue_type: "Technical Issue",
      description: "The slide presentation was not working properly during the keynote",
      status: "pending",
      created_at: "2024-05-28T15:30:00Z",
      events: { title: "Tech Summit 2024" },
      profiles: { name: "John Attendee" }
    },
    {
      id: "2",
      event_id: "2",
      user_id: "4",
      issue_type: "Audio Problem",
      description: "The speaker's microphone had feedback issues during the second session",
      status: "approved",
      created_at: "2024-05-27T12:45:00Z",
      events: { title: "AI Workshop" },
      profiles: { name: "Sarah Participant" }
    },
    {
      id: "3",
      event_id: "5",
      user_id: "5",
      issue_type: "Inappropriate Content",
      description: "One of the slides contained potentially offensive material",
      status: "pending",
      created_at: "2024-05-26T09:15:00Z",
      events: { title: "Design Thinking Workshop" },
      profiles: { name: "Michael Jones" }
    }
  ],
  analytics: {
    eventAttendance: [
      { name: "Tech Summit 2024", attendees: 420 },
      { name: "AI Workshop", attendees: 135 },
      { name: "Developer Conference", attendees: 280 },
      { name: "Startup Pitch Day", attendees: 175 },
      { name: "Design Thinking Workshop", attendees: 90 }
    ],
    userGrowth: [
      { name: "Jan", month: "Jan", users: 50 },
      { name: "Feb", month: "Feb", users: 120 },
      { name: "Mar", month: "Mar", users: 200 },
      { name: "Apr", month: "Apr", users: 280 },
      { name: "May", month: "May", users: 350 },
      { name: "Jun", month: "Jun", users: 450 }
    ],
    featureUsage: [
      { name: "Event Registration", count: 1250 },
      { name: "Mic Requests", count: 320 },
      { name: "QR Check-ins", count: 980 },
      { name: "Feedback Submissions", count: 540 },
      { name: "Live Polls", count: 720 }
    ],
    topEvents: [
      { id: "1", title: "Tech Summit 2024", attendees: 420, capacity: 500, fillRate: 84 },
      { id: "2", title: "AI Workshop", attendees: 135, capacity: 150, fillRate: 90 },
      { id: "3", title: "Developer Conference", attendees: 280, capacity: 300, fillRate: 93 },
      { id: "4", title: "Startup Pitch Day", attendees: 175, capacity: 200, fillRate: 88 },
      { id: "5", title: "Design Thinking Workshop", attendees: 90, capacity: 100, fillRate: 90 }
    ]
  },
  feedbacks: [
    {
      id: 'feedback-1',
      user_id: '3',
      event_id: '1',
      rating: 5,
      comment: 'Great presentation!',
      created_at: '2023-01-01T00:00:00.000Z',
      profiles: { name: 'John Attendee' },
      events: { title: 'Tech Summit 2024' }
    },
    {
      id: 'feedback-2',
      user_id: '4',
      event_id: '2',
      rating: 4,
      comment: 'Very informative session.',
      created_at: '2023-01-02T00:00:00.000Z',
      profiles: { name: 'Sarah Participant' },
      events: { title: 'AI Workshop' }
    },
    {
      id: 'feedback-3',
      user_id: '5',
      event_id: '3',
      rating: 3,
      comment: 'Room for improvement',
      created_at: '2023-01-03T00:00:00.000Z',
      profiles: { name: 'Michael Jones' },
      events: { title: 'Developer Conference' }
    }
  ]
};

// Add typescript helper function that properly handles errors in query results
export const handleQueryResult = <T>(data: T | null, error: any): { data: T | null, error: any } => {
  if (error) {
    console.error("Database query error:", error);
    return { data: null, error };
  }
  
  if (!data) {
    return { data: null, error: new Error("No data returned") };
  }
  
  return { data, error: null };
};

// Utility function to safely cast types
export function safeCast<T>(data: any): T {
  return data as T;
}

// Static mode helper for demo presentations
export const getStaticData = <T>(dataType: keyof typeof staticDemoData, useStatic: boolean = true): T => {
  return staticDemoData[dataType] as T;
};
